name: Publish Library to Npm
run-name: ${{ github.actor }} is publishing to npm
on:
  push:
    branches:
      - main
jobs:
  Publish-to-Npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Replace with your desired Node.js version
      - name: Set up Yarn
        run: |
          npm install -g yarn
      - name: Install dependencies with Yarn
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Publish to Npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}